program: 02_on_policy_eval.py
name: 02_on_policy_eval
project: 02_on_policy_eval
description: 02_on_policy_eval
method: grid
metric:
  goal: minimize
  name: ground_truth_value_error
parameters:
  env_size: 
    values: [5]
    # values: [5, 10, 20]
  policy_id:
    values: [850]
  num_train_episode:
    values: [10000]
  repeat:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
