program: 03_behavior_policy_search.py
name: 03_bpg_eval
project: 03_bpg_eval
description: 03_bpg_eval
method: grid
metric:
  goal: minimize
  name: ground_truth_value_error
parameters:
  env_size: 
    values: [3]
    # values: [5, 10, 20]
  policy_id:
    values: [850]
  num_train_episode:
    values: [10000]
