program: 03_behavior_policy_search.py
name: 03_bpg_eval
project: 03_bpg_eval
description: 03_bpg_eval
method: grid
metric:
  goal: minimize
  name: ground_truth_value_error
parameters:
  env_size: 
    values: [5]
    # values: [5, 10, 20]
  policy_id:
    values: [850]
  num_train_episode:
    values: [1000]
  repeat:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
