wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1687709791.553461
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.9.16
      5: 0.13.11
      8:
      - 5
description:
  desc: null
  value: 02_on_policy_eval
env_size:
  desc: null
  value: 5
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: minimize
    name: ground_truth_value_error
name:
  desc: null
  value: 02_on_policy_eval
num_train_episode:
  desc: null
  value: 10000
parameters:
  desc: null
  value:
    env_size:
      values:
      - 5
    num_train_episode:
      values:
      - 10000
    policy_id:
      values:
      - 850
policy_id:
  desc: null
  value: 850
program:
  desc: null
  value: 02_on_policy_eval.py
project:
  desc: null
  value: 02_on_policy_eval
